<%
	' This file should only include the class definitions so as it can
	' be used as a common include on pages that will use classes
	'
%>
<!-- #include file="classes/cTimer.asp" -->
<!-- #include file="classes/User.inc" -->
<!-- #include file="classes/UserAccountSecurity.inc" -->
<!-- #include file="classes/UserBranchSecurity.inc" -->
<!-- #include file="classes/UserDocumentViewAccess.inc" -->
<!-- #include file="classes/UserPermission.inc" -->
<!-- #include file="classes/UserSecurity.inc" -->