<link rel="stylesheet" type="text/css" href="Packages/fontawesome/css/all.min.css">
<link rel="stylesheet" type="text/css" href="Packages/jquery-ui/jquery-ui.css"/>
<link rel="stylesheet" type="text/css" href="Packages/kendo-ui/styles/kendo.common.min.css"/>
<link rel="stylesheet" type="text/css" href="Packages/kendo-ui/styles/kendo.common-material.min.css"/>
<link rel="stylesheet" type="text/css" href="Packages/kendo-accuaccount/styles/kendo.custom.css"/>
<link rel="stylesheet" type="text/css" href="Content/App/App.all.min.css"/>
<link rel="stylesheet" type="text/css" href="Content/Core.Modal.css"/>
<link rel="stylesheet" type="text/css" href="Content/Kendo.Custom.css"/>
<link rel="stylesheet" type="text/css" href="Content/Dhtmlx.Custom.css"/>
